apiVersion: v1
kind: Pod
metadata:
  name: command-args-demo
spec:
  containers:
  - name: command-args-ctr
    image: debian 
    imagePullPolicy: IfNotPresent
    command: ["printenv"]
    args: ["KUBERNETES_PORT", "HOSTNAME"]
  restartPolicy: OnFailure


---
apiVersion: v1 
kind: Pod
metadata:
  name: com-args-demo
spec:
  containers:
  - name: com-args-demo
    image: debian
    env:
      - name: "MYVAR"
        value: "ExposedPort"
    args:
      - printenv
      - KUBERNETES_PORT
      - HOSTNAME
      - MYVAR
  restartPolicy: OnFailure
