apiVersion: v1
kind: Pod
metadata:
  name: downward-vol-demo
  labels:
    zone: Hyderabad
    region: telangana
    country: India
  annotations: 
    build: docker
    builder: sundeep Eamani
spec:
  containers:
  - name: downward-vol-ctr
    image: busybox
    args:
      - sh
      - -c
      - while true; do
        if [[ -e /etc/podinfo/labels ]]; then
        echo; cat /etc/podinfo/labels; fi;
        if [[ -e /etc/podinfo/annotations ]]; then
        echo; cat /etc/podinfo/annotations; fi;
        if [[ -e /etc/podinfo/cpurequest ]]; then
        echo -en "\n\n"; cat /etc/podinfo/cpurequest; fi;
        if [[ -e /etc/podinfo/limitmemory ]]; then
        echo -en "\n\n"; cat /etc/podinfo/limitmemory; fi;
        sleep 10; done;
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1G"
    volumeMounts:
      - name: downward-vol
        mountPath: /etc/podinfo
  volumes:
    - name: downward-vol
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "cpurequest"
            resourceFieldRef:
              containerName: downward-vol-ctr
              resource: requests.cpu
          - path: "limitmemory"
            resourceFieldRef:
              containerName: downward-vol-ctr
              resource: limits.memory
