apiVersion: v1
kind: Pod
metadata: 
  name: pod-field-demo
spec:
  containers:
  - name: pod-field-ctr
    image: debian
    args:
      - printenv 
      - NODE_NAME
      - POD_NAME
      - NAMESPACE_NAME
      - POD_IP

    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NAMESPACE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  restartPolicy: OnFailure
