---
apiVersion: v1
kind: Pod
metadata:
  name: pod-practice
  labels:
    name: hello-pod
spec:
  containers:
  - name: hello-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP




