apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jenkins-deployment-demo
  labels:
    app:  jenkins-deploy-demo
spec:
  replicas: 4
  strategy:
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app : jenkins
    spec:
      containers:
      - image: nginx
        name:  jenkins-container
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "200m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        imagePullPolicy: Always
        ports:
        - containerPort:  8080
          name: jenkins-port
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
