apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy-demo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-ctr
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        volumeMounts:
          - name: my-persistent-storage
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql-port
      volumes:
        - name: my-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim 

