apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-demo
spec:
  selector:
    matchLabels: 
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deploy-demo
        image: nginx:1.16.1
        ports:
        - containerPort: 80
